---
"t1sdfsdf": 
  "c": "kls  kjhfdgh"
  "i": ""
  "l": 1
  "o": ""
  "p": "lksdf  gjdfg"
  "t": "lsjkd lghj"
  "w": 0
"t2": 
  "c": "klskjhfdgh"
  "i": ""
  "l": 1
  "o": ""
  "p": "lksdfgjdfg"
  "t": "lsjkdfgklghj"
  "w": 0
...