---
"AI": 
  "title": "test sessie"
"AI23": 
  "title": "test sessie"
"AI24": 
  "title": "test sessie"
"Default": 
  "group1": 
    "title": "default setup"
  "title": "test sessie"
"Default2": 
  "title": "test sessie2"
...