---
"AI23b": 
  "group1": 
    "actions": 
      - "DHome3"
    "title": "g1"
  "group2": 
    "actions": 
      - "DHome"
      - "kHome"
    "title": "g2"
  "group3": 
    "actions": 
      - "DHome"
      - "kHome"
    "title": "g2"
  "group4": 
    "actions":  []
    "title": "g2"
  "group5": 
    "actions":  []
    "title": "g2"
  "icon": "/mnt/E4-8-TB/.Old/AI/ComfyUI/Lady D1/Futa/Futa 19/LD1-18-13_00031_.png"
  "over": "/mnt/E4-8-TB/.Old/AI/ComfyUI/Lady D1/Futa/Futa 19/LD1-18-13_00031_.png"
  "title": "should have a text here"
"manager": 
  "group1": 
    "actions": 
      - "DHome"
    "title": "my g1"
  "group2": 
    "actions": 
      - "DHome"
      - "kHome"
    "title": "my g2"
  "group3": 
    "actions": 
      - "kHome"
    "title": "my g1"
  "group4": 
    "actions":  []
    "title": "my g1"
  "title": "test sessie"
"xxx": 
  "group1": 
    "actions":  []
  "icon": "/mnt/E4-8-TB/.Old/AI/ComfyUI/Lady D1/Futa/Futa 16/LD1-13-02_00030_.png"
  "over": "/mnt/E4-8-TB/.Old/AI/ComfyUI/Lady D1/Futa/Futa 16/LD1-13-02_00033_.png"
  "title": "xxx"
...