---
"AI23b": 
  "group1": 
    "actions":  []
    "title": "g1"
  "group2": 
    "actions": 
      - "DHome"
      - "kHome"
    "title": "g2"
  "group3": 
    "actions": 
      - "DHome"
      - "kHome"
    "title": "g2"
  "group4": 
    "actions":  []
    "title": "g2"
  "group5": 
    "actions":  []
    "title": "g2"
  "title": "should have a text here"
"manager": 
  "group1": 
    "actions": 
      - "DHome"
    "title": "my g1"
  "group2": 
    "actions": 
      - "DHome"
      - "kHome"
    "title": "my g2"
  "group3": 
    "actions": 
      - "kHome"
    "title": "my g1"
  "group4": 
    "actions":  []
    "title": "my g1"
  "title": "test sessie"
...