---
"AI23a": 
  "group1": 
    "actions": 
      - "kHome"
    "title": "jhsgdf jhsgd f jhgsrwueit"
  "title": "should have e text here?"
"manager": 
  "group1": 
    "actions":  []
  "title": "test sessie"
...