---
"AI": 
  "title": "test sessie"
"AI2": 
  "title": "test sessie"
"AI3": 
  "title": "test sessie"
"AI4": 
  "title": "test sessie"
"Default": 
  "group1": 
    "title": "default setup"
  "title": "test sessie"
"Default2": 
  "title": "test sessie2"
...